### ISSUE TITLE
mac下交叉编译linux(debian)，出现错误

### ISSUE THREAD

**Issue by willgeek** [snail007/gmc#8]
mac下交叉编译linux(debian)，出现错误，mac正常运行
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x9108d9]

goroutine 1 [running]:
main.main()
        /admin/main.go:26 +0x199`

**Comment by snail007** [comment]
请提供完整的case，方便进一步分析，目前你提供的信息无法分析出问题所在。

**Comment by sayue2019** [comment]
直接Linux编译了
