### ISSUE TITLE
使用gmct工具生成的api项目，go mod tidy时报错

### ISSUE THREAD

**Issue by sayue2019** [snail007/gmc#9]
mac使用gmct工具生成的api项目，在使用go mod tidy时报错，提示没有github.com/snail007/gmc/http
github.com/snail007/gmc/http: module github.com/snail007/gmc@latest found (v0.0.0-20220302025423-574b4fe03638), but does not contain package github.com/snail007/gmc/http

**Comment by snail007** [comment]
应该是api代码比较陈旧了，使用最新的gmc需要调整一下，后面我更新一下api代码。

**Comment by snail007** [comment]
我复现了一下，发现并不是代码问题，是本地go mod缓存问题，执行：`go clean -modcache` 清理一下本地mod缓存即可，然后 go mod tidy即可正常。
